site_name: Endades Documentation

plugins:
  - search
  - i18n:
      default_language: es
      docs_structure: folder
      languages:
        - locale: es
          name: Español
          default: true
          build: true
          nav:
            - Inicio: index.md
            - Configuraciones:
              - Configuración Inicial ENBLAU: Configuraciones/1. CO_Configuracion_Inicial_ENBLAU.md
              - Configuración Inicial enCONTROL: Configuraciones/2. CO_Configuracion_Inicial_enCONTROL.md
            - Procesos:
              - Ventas y Compras: Procesos/1.PR_Ventas_Compras.md
              - Facturación: Procesos/2.PR_Facturas.md
              - Géstion de control de stock ENBLAU: Procesos/3.PR_Manual_Stock_ENBLAU.md
              - Géstion de control de stock enCONTROL: Procesos/4.PR_Manual_Stock_enCONTROL.md
              - Informes: Procesos/5.PR_Informes.md
              - Proyectos, Clientes y Proveedores: Procesos/6.PR_Proyecto_cliente.md
              - Instalaciones: Procesos/7.PR_Instalaciones.md
            - Utilidades:
              - Relación entre fases en ENBLAU y Logikal: Utilidades/1.UT_Relacion_ENBLAU_Logikal.md
              - Creación de materiales propios en enMATERIALS: Utilidades/2.UT_Crear_Materiales_enMATERIAL.md
              - Creación y edición de informes personalizados: Utilidades/3.UT_Editar_Informes.md
              - Gestión de filtros: Utilidades/4.UT_Gestion_Filtros.md
              - Actualización ENBLAU: Utilidades/5.UT_Actualizar_ENBLAU.md
              - Conectar una Unidad de Red: Utilidades/6.UT_Unidad_Red.md
              - Divisas: Utilidades/7.UT_Divisas.md
              - Importación programa de contabilidad: Utilidades/8.UT_Importacion_Contabilidad.md
              - Escandallos (Agrupación de materiales): Utilidades/9.UT_Escandallos.md
              - Tarifas y Mano de obra (materiales ENBLAU): Utilidades/10.UT_Tarifas.md
        - locale: en
          name: English
          build: true
          nav:
            - Home: index.md
            - Configurations:
              - Initial Configuration ENBLAU: Configurations/1. CO_Configuracion_Inicial_ENBLAU.md
              - Initial Configuration enCONTROL: Configurations/2. CO_Configuracion_Inicial_enCONTROL.md
            - Processes:
              - Sales and Purchases: Processes/1.PR_Ventas_Compras.md
              - Invoicing: Processes/2.PR_Facturas.md
              - Stock Control Management ENBLAU: Processes/3.PR_Manual_Stock_ENBLAU.md
              - Stock Control Management enCONTROL: Processes/4.PR_Manual_Stock_enCONTROL.md
              - Reports: Processes/5.PR_Informes.md
              - Projects, Clients and Suppliers: Processes/6.PR_Proyecto_cliente.md
              - Installations: Processes/7.PR_Instalaciones.md
            - Utilities:
              - Relationship between phases in ENBLAU and Logikal: Utilities/1.UT_Relacion_ENBLAU_Logikal.md
              - Creation of custom materials in enMATERIALS: Utilities/2.UT_Crear_Materiales_enMATERIAL.md
              - Creation and editing of custom reports: Utilities/3.UT_Editar_Informes.md
              - Filter management: Utilities/4.UT_Gestion_Filtros.md
              - ENBLAU update: Utilities/5.UT_Actualizar_ENBLAU.md
              - Connect a Network Unit: Utilities/6.UT_Unidad_Red.md
              - Currencies: Utilities/7.UT_Divisas.md
              - Import accounting program: Utilities/8.UT_Importacion_Contabilidad.md
              - Bill of materials (Grouping of materials): Utilities/9.UT_Escandallos.md
              - Rates and Labor (materials in ENBLAU): Utilities/10.UT_Tarifas.md
        - locale: it
          name: Italiano
          build: true
          nav:
            - Home: index.md
            - Configurazioni:
              - Configurazione iniziale ENBLAU: Configurazioni/1. CO_Configuracion_Inicial_ENBLAU.md
              - Configurazione iniziale enCONTROL: Configurazioni/2. CO_Configuracion_Inicial_enCONTROL.md
            - Processi:
              - Vendite e Acquisti: Processi/1.PR_Ventas_Compras.md
              - Fatturazione: Processi/2.PR_Facturas.md
              - Gestione del controllo delle scorte ENBLAU: Processi/3.PR_Manual_Stock_ENBLAU.md
              - Gestione del controllo delle scorte enCONTROL: Processi/4.PR_Manual_Stock_enCONTROL.md
              - Rapporti: Processi/5.PR_Informes.md
              - Progetti, Clienti e Fornitori: Processi/6.PR_Proyecto_cliente.md
              - Installazioni: Processi/7.PR_Instalaciones.md
            - Utilità:
              - Relazione tra fasi in ENBLAU e Logikal: Utilita/1.UT_Relacion_ENBLAU_Logikal.md
              - Creazione di materiali propri in enMATERIALS: Utilita/2.UT_Crear_Materiales_enMATERIAL.md
              - Creazione e modifica di rapporti personalizzati: Utilita/3.UT_Editar_Informes.md
              - Gestione dei filtri: Utilita/4.UT_Gestion_Filtros.md
              - Aggiornamento ENBLAU: Utilita/5.UT_Actualizar_ENBLAU.md
              - Connessione di un'Unità di Rete: Utilita/6.UT_Unidad_Red.md
              - Valute: Utilita/7.UT_Divisas.md
              - Importazione programma di contabilità: Utilita/8.UT_Importacion_Contabilidad.md
              - Bill of materials (Grouping of materials): Utilita/9.UT_Escandallos.md
              - Tariffe e Manodopera dei (materiali in ENBLAU): Utilita/10.UT_Tarifas.md
        - locale: pt
          name: Português
          build: true
          nav:
            - Home: index.md
            - Configurações:
              - Configuração inicial ENBLAU: Configurações/1. CO_Configuracion_Inicial_ENBLAU.md
              - Configuração inicial enCONTROL: Configurações/2. CO_Configuracion_Inicial_enCONTROL.md
            - Processos:
              - Vendas e Compras: Processos/1.PR_Ventas_Compras.md
              - Facturação: Processos/2.PR_Facturas.md
              - Gestão de controlo de stock ENBLAU: Processos/3.PR_Manual_Stock_ENBLAU.md
              - Gestão de controlo de stock enCONTROL: Processos/4.PR_Manual_Stock_enCONTROL.md
              - Relatórios: Processos/5.PR_Informes.md
              - Projetos, Clientes e Fornecedores: Processos/6.PR_Proyecto_cliente.md
              - Instalacões: Processos/7.PR_Instalaciones.md
            - Utilidades:
              - Relação entre fases em ENBLAU e Logikal: Utilidades/1.UT_Relacion_ENBLAU_Logikal.md
              - Criação de materiais próprios em enMATERIALS: Utilidades/2.UT_Crear_Materiales_enMATERIAL.md
              - Criação e edição de relatórios personalizados: Utilidades/3.UT_Editar_Informes.md
              - Gestão de filtros: Utilidades/4.UT_Gestion_Filtros.md
              - Atualização ENBLAU: Utilidades/5.UT_Actualizar_ENBLAU.md
              - Conectar uma Unidade de Rede: Utilidades/6.UT_Unidad_Red.md
              - Moedas: Utilidades/7.UT_Divisas.md
              - Importação programa de contabilidade: Utilidades/8.UT_Importacion_Contabilidad.md
              - Escandallos (Agrupación de materiales): Utilidades/9.UT_Escandallos.md
              - Tarifas e Mão de Obra (materiais no ENBLAU): Utilidades/10.UT_Tarifas.md

theme:
  name: readthedocs
  highlightjs: true
  custom_dir: overrides

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - js/lang-switcher.js

extra:
  hide:
    github: true
    edit_page: true

copyright: " "